Ensono/stacks-dotnet

src/api/NuGet.config
src/api/README.md

[XXXX-<Title> - Please use the Work Item number and Title as PR Name, not subtasks]
Removed out dated Nuget config items and updated README
Notes for QA

fix: remove STACKS_NUGET and update README

---

build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
deploy/azure/app/kube/main.tf
deploy/azure/app/kube/outputs.tf
deploy/azure/app/kube/vars.tf
deploy/k8s/app/base_api-deploy.yml

[XXXX-<Title> - Please use the Work Item number and Title as PR Name, not subtasks]
store build and deploy v2 folders within stacks-dotnet repo
Update and clean up CLI project
Notes for QA

Task: add support for v2 stacks

---

src/api/xxAMIDOxx.xxSTACKSxx.API.ContractTests/ReadMe.md
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Builders/CategoryRequestBuilder.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Builders/MenuItemBuilder.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Models/Category.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Models/CreateObjectResponse.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/ReadMe.md
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Steps/CategorySteps.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Steps/ItemSteps.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Steps/MenuSteps.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Stories/CreateCategoryTests.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Stories/CreateItemTests.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Stories/DeleteCategoryTests.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Stories/DeleteItemTests.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Stories/UpdateCategoryById.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/Tests/Stories/UpdateItemById.cs
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/appsettings.json

Add API tests for Create/Update/Delete Categories and Items

Add API tests

---

src/api/xxAMIDOxx.xxSTACKSxx.API.ComponentTests/xxAMIDOxx.xxSTACKSxx.API.ComponentTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.API.ContractTests/xxAMIDOxx.xxSTACKSxx.API.ContractTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.API/xxAMIDOxx.xxSTACKSxx.API.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Application.QueryHandlers/xxAMIDOxx.xxSTACKSxx.Application.QueryHandlers.csproj
src/api/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.CQRS/xxAMIDOxx.xxSTACKSxx.CQRS.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Common.UnitTests/xxAMIDOxx.xxSTACKSxx.Common.UnitTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Common/xxAMIDOxx.xxSTACKSxx.Common.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Domain.UnitTests/xxAMIDOxx.xxSTACKSxx.Domain.UnitTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Domain/xxAMIDOxx.xxSTACKSxx.Domain.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure.IntegrationTests/xxAMIDOxx.xxSTACKSxx.Infrastructure.IntegrationTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/xxAMIDOxx.xxSTACKSxx.Infrastructure.csproj
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests.csproj

Upgrading NuGet packages.
Warnings are currently appearing on builds where Amido NuGet package versions do not exist.
3rd Party NuGets also being upgraded

#152-Upgrading NuGet packages

---

build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
build/azDevOps/azure/templates/steps/build-netcore.yml
yamllint.conf

Adds YAMLLint and TF `fmt` & `validate` steps, this brings dotnet in line with all the other repos which now have the linting in place.

Adds YAMLLint and TF fmt/validate steps

---

build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
deploy/azure/app/kube/constraints.tf
deploy/azure/app/kube/main.tf
src/api/xxAMIDOxx.xxSTACKSxx.Common/Exceptions/DomainRuleViolationException.cs
src/api/xxAMIDOxx.xxSTACKSxx.Common/Exceptions/MenuAlreadyExistsException.cs
src/api/xxAMIDOxx.xxSTACKSxx.Common/Exceptions/MenuDoesNotExistException.cs
src/api/xxAMIDOxx.xxSTACKSxx.Common/Exceptions/OperationFailedException.cs

- Upgrades TF to 0.13
- Upgrades Pipeline to use better envs (test) and deploy master to
only Prod, not Dev and Prod
- Use the newer (not deprecated) Base Exception Method

feat: Upgrades TF to 0.13

---

src/api/xxAMIDOxx.xxSTACKSxx.API.ComponentTests/xxAMIDOxx.xxSTACKSxx.API.ComponentTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.API.ContractTests/xxAMIDOxx.xxSTACKSxx.API.ContractTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.API/xxAMIDOxx.xxSTACKSxx.API.csproj
src/api/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests/xxAMIDOxx.xxSTACKSxx.CQRS.UnitTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.CQRS/xxAMIDOxx.xxSTACKSxx.CQRS.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Common/xxAMIDOxx.xxSTACKSxx.Common.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Domain/xxAMIDOxx.xxSTACKSxx.Domain.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure.IntegrationTests/xxAMIDOxx.xxSTACKSxx.Infrastructure.IntegrationTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.Infrastructure/xxAMIDOxx.xxSTACKSxx.Infrastructure.csproj
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests.sln
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests.csproj

3006 - Update packages on stacks-dotnet
📲 What
Updating Microsoft packages to 3.1.16 (June 21 release)
Updating internal nuget packages to recently updated version
Updating third party packages to latest stable version
🤔 Why
To prevent vulnerabilities
🛠 How
Updating packages
🕵️ How to test
Run tests again
✅ Acceptance criteria Checklist

3006 - Update packages on stacks-dotnet

---

build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
build/azDevOps/azure/templates/steps/build/build-netcore.yml

Re-enabled the functional tests for .NET WebApi
[AB#3129](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/3129)
To ensure that everything has deployed properly
Enabled the variables to allow the functional tests to be run
Updated the version of the `stacks-pipeline-templates` that are being used as they have the correct YAML to run the functional tests
Functional tests are being run and results are being published
Notes for QA

[3129] Add execution of tests to pipeline

---

.template.config/template.json
template.csproj

Add templates project
Added csproj to deploy it as a NuGet package
So then, we can have versions of it

Adding templates project

---

build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
template.csproj

Update the exclusion list in the template file.
The `template.csproj` did not have the correct list of exclusions which meant that the Nuget package had files that were are not required.
Modified the `template.csproj` with the correct list of exlusions:
```
<Content Include=".\templates\**" Exclude=".\templates\**\.git\**;.\templates\**\.github\**;.\templates\**\.vscode\**;.\templates\**\obj\**;.\templates\**\bin\**;.\templates\**\.terraform\**;.\templates\**\.store\**;.\templates\**\template.csproj" />
```
The filesize of the nuget package is now much smaller.

Updated template exclusions

---

README.md

[3227 - Add template information to README]
Documentation for the installation and usage of templates
People re-writing the CLI or just using the templates themselves have to know how to use our templates.
Notes for QA

Update README with template information

---

src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Category/AddMenuCategoryController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Category/DeleteCategoryController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Category/UpdateMenuCategoryController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Item/AddMenuItemController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Item/DeleteMenuItemController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Item/UpdateMenuItemController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Menu/CreateMenuController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Menu/DeleteMenuController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Menu/GetMenuByIdController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Menu/SearchMenuController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Menu/UpdateMenuController.cs

[3534 - Fix warnings]
Fix all CS1998 warnings
We want to provide a template that builds without any warnings
Our controllers are `async` but didn't have any `await` code. I've added a simple `await Task.CompletedTask` to resolve the problem
Notes for QA

Fix warnings (CS1998)

---

build/azDevOps/azure/azure-pipelines-netcore-k8s.yml
build/azDevOps/azure/azuredevops-vars.yml

Move variables out of main build file into separate variable template file
By making the variables a separate file it is easier to automate its creation in the Stacks CLI
All of the variables are written to the variable template file, `azuredevops-vars.yaml`. This is included in the main build file.
The builds are working as before
Notes for QA

[3642] Use variable template for stacks-dotnet

---

src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Item/AddMenuItemController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Item/DeleteMenuItemController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Controllers/Item/UpdateMenuItemController.cs
src/api/xxAMIDOxx.xxSTACKSxx.API/Startup.cs

3901 - Fix typos and inconsistencies
Fix typos and inconsistencies
These issues were flagged to us from developers who tested Stacks
Notes for QA

Fix typos and inconsistencies

---

.template.config/dotnetcli.host.json
.template.config/template.json
README.md

3902 - Unify CLI template arguments
We want the CLI arguments to be unified between all templates
So we can have consistency throughout our offering
Notes for QA

Unify CLI template arguments

---

stackscli.yml

Allow the CLI to check the version of a framework tool
Projects may require a specific version of framework tools
The CLI has been updated so that the `stackscli.yml` file can now specify the constraints of a framework tool
This is based on semantic versioning and allows the CLI to check if the correct version of tools are available for each project
CLI Documentation has been updated with the new structure and an example of the user interaction
Notes for QA

[3949] CLI framework version check 

---

src/api/xxAMIDOxx.xxSTACKSxx.API.UnitTests/xxAMIDOxx.xxSTACKSxx.API.UnitTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.API/xxAMIDOxx.xxSTACKSxx.API.csproj
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests.csproj

Update Nuget Packages for stacks-dotnet
Update of all nuget packages in the solution that are now out of date.
Improve security vulnerabilities
Running update packages on the solution.
Notes for QA

Update Nuget Packages for stacks-dotnet

---

src/api/xxAMIDOxx.xxSTACKSxx.API.UnitTests/xxAMIDOxx.xxSTACKSxx.API.UnitTests.csproj
src/api/xxAMIDOxx.xxSTACKSxx.API/xxAMIDOxx.xxSTACKSxx.API.csproj
src/tests/Functional/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests/xxAMIDOxx.xxSTACKSxx.API.FunctionalTests.csproj

Fix Snyk vulnerabilities and bump dependencies
Changes:
- api: Fix snyk vulnerabilities and update dependencies
- functional-tests: Fix snyk vulnerabilities and update dependencies
Upgrade form vunlerable packages	
CI Build/Automated tests

Fix snyk vulnerabilities and update dependencies

---

build/azDevOps/azure/azure-pipelines-netcore-k8s.yml

[Bug-4313: NuGet Package Publish Failing]
Resolving the NuGet publish feature which is failing in the release stage of the pipeline
To publish the NuGet packages
By running the pipeline 
Notes for QA

Bug-4313: Fix NuGet Package Publish Failing

---

build/azDevOps/azure/air-api.yml
build/azDevOps/azure/nuget-packages-api.yml
build/taskctl/contexts.yaml
deploy/azure/app/kube/lookups.tf
deploy/azure/app/kube/main.tf

[XXXX-<Title> - Please use the Work Item number and Title as PR Name, not subtasks]
Removes trailing spaces
Paramaterises Core Environment TF var
Migrates Data Lookup to separate file
Quality of life changes
Standard TF
[Build](https://dev.azure.com/amido-dev/Amido-Stacks/_build/results?buildId=21682&view=logs&j=29282bd1-74ac-52dd-c0da-b964965d8861&t=90a2b02d-1030-5632-433d-f9395afc6cca&l=410)
Notes for QA

QoL Updates

---

build/azDevOps/azure/air-api-vars.yml
build/azDevOps/azure/air-api.yml
build/taskctl/tasks.yaml
taskctl.yaml

Amends code coverage parameters for dotnet build process.
Report coverage properly into SonarQube
Standard ADO YML/Powershell parameter update.
[Sonarqube](https://sonarcloud.io/summary/overall?id=stacks-dotnet)
[Build](https://amido-dev.visualstudio.com/Amido-Stacks/_build?definitionId=170)
Review coverage in SonarQube and see it is present.

BUGFIX: Amends Code Coverage Parameters

---

build/azDevOps/azure/air-api-vars.yml
build/taskctl/tasks.yaml

Amends Coverage target for ADO
To view ADO code coverage
Command call change in AIR
N/A
Notes for QA

Amends Coverage target for ADO

---

.github/workflows/ci.yml
build/azDevOps/azure/air-api.yml
build/deployment_list.ps1
deploy/k8s/aws/base_api-deploy.yml

Updates Triggers and Logging Info
Update Backend Args for TF deployment in ADO/Azure
So ADO/Azure builds only trigger on some paths, and Github/AWS builds trigger on the other.
Standard pathing filters.
Notes for QA

Updates Triggers and Logging Info

---

.template.config/dotnetcli.host.json
.template.config/template.json
README.md

[AB#4704](https://amido-dev.visualstudio.com/73884c9a-a68f-4f67-b2b5-b588c2eb8492/_workitems/edit/4704) - Implement cloud provider selection for dotnet templates
Implement cloud provider selection for dotnet templates
Remove DevOps build files when not required based on a cloud provider selection 
Notes for QA

AB#4704 - Implement cloud provider selection for dotnet templates

---

.template.config/dotnetcli.host.json
.template.config/template.json
README.md

Add CiCd provider option to the package
📲 What
Add CiCd provider option to the package
🤔 Why
Enable better context for exclusions based around both CICD and cloud provider.
Notes for QA

Add CiCd provider option to the package

---

build/azDevOps/azure/air-api-vars.yml
build/azDevOps/azure/air-api-vars_TEMPLATE.yml
build/taskctl/tasks.yaml

Updates templates files
To accommodate additional variables required for Helm
Standard YML
N/A
Notes for QA

BUGFIX: Updates templates file for Helm vars

---

build/azDevOps/azure/air-api-vars.yml
build/azDevOps/azure/air-api-vars_TEMPLATE.yml
build/azDevOps/azure/air-api.yml
build/taskctl/contexts.yaml

Updates Runner Image
Workspace compatibility
Standard context update
See linked build
Notes for QA

Updates Runner Image

---

.github/workflows/ci.yml

Update prod deployment to use the new AWS cluster

fix: update prod deployment for new cluster

---

.github/workflows/ci.yml
build/github/aws/ci_TEMPLATE.yml

A fix to only supply PR Parameters for Sonar on a PR
master is complaining about an empty PR Key

fix: fixes master with no PR params

---

.github/pull_request_template.md
.github/workflows/ci.yml
build/deployment_list.ps1
build/github/aws/ci_TEMPLATE.yml
deploy/aws/app/kube/data.tf
deploy/aws/app/kube/variables.tf
deploy/helm/stacks-dotnet/values.yaml
taskctl.yaml

Fixes URLs again
Prod is Broken and Dev is Wrong

fix: prod functional test URL

---

scripts/README.md

Nice formatting of the directory structure.
It was badly formatted.
Code block
N/A
N/A

fix: Nice formatting of the directory structure.

---

.github/dependabot.yml

Update dependabot directories for the new structure.
-
-
-
-

fix: update dependabot directories

---

README.md

Summary:
Updated the README to include details for all templates.
The README was out of date.

fix: 7688 update the readme to include details of all templates

---

docs/infrastructure.adoc

fix: 7688 rogue amido reference

---

scripts/test-templates.sh

fix: test-template.sh script as the pathing has changed slightly
Fixed test script is better

fix: test-template.sh script as the pathing has changed slightly

---

scripts/test-templates.sh
src/simple-api/src/api/xxENSONOxx.xxSTACKSxx.API.sln

Fix Added CQRS template
Added CQRS template was failing

8056 - Fix Added CQRS template

---

src/background-worker/.template.config/template.json
src/func-aeh-listener/.template.config/template.json
src/func-asb-listener/.template.config/template.json
src/func-cosmosdb-worker/.template.config/template.json

Fix: Remove shared projects from function templates

7710 - Fix: Remove shared projects from function templates

---

scripts/test-templates.sh

Added fleshed out CQRS generated templates

refactor: Added fleshed out CQRS generated templates

---

src/background-worker/.template.config/template.json
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.API.ComponentTests/Fixtures/CreateCategoryFixture.cs
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/Configuration.cs
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/CosmosDb/DataModel/SampleEntity.cs
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/CosmosDb/Integration/CosmosDbDocumentStorageIntegrationTests.cs
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/CosmosDb/Integration/CosmosDbDocumentStorageQueriesIntegrationTests.cs
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/CosmosDb/Integration/IntegrationFixture.cs
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/CosmosDbMenuRepositoryTests.cs
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/DotEnv.cs
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/MenuRepositoryAutoData.cs
src/func-aeh-listener/.template.config/template.json
src/func-asb-listener/.template.config/template.json
src/func-cosmosdb-worker/.template.config/template.json
src/simple-api/.template.config/template.json

Removed references to template.json files 
Fixed usings in tests that have been commented out using a preprocessor

fix: 7738 all the fixes for shared testing

---

scripts/test-templates.sh

When running the script to test the templates, on my computer I found when I got as far as the EventHib.Listener template, the  script couldn't find the solution, so was unable to run the tests.  The templates that followed on from this templates also experienced the same issue.  This PR adjusts the script so that these later template test can run.
Tests were not run, on my computer, for seven templates all-together.
The relative paths used in the template paths have been replaced with fixed paths, which are declared at the beginning of the script.  Also, a test run has been added for the Add-CQRS template, but I'm unsure if this is necessary as it may be covered by one of the other runs.
The screenshot below shows the issue where some of my tests failed to run: -
The screenshot below …

test-templates script:  Replace relative paths with fixed paths

---

deploy/azure/app/function/function.tf
src/func-aeh-listener/src/functions/Dockerfile
src/func-asb-listener/src/functions/Dockerfile
src/func-cosmosdb-worker/src/functions/Dockerfile

Update runtime image for Azure Functions to mcr.microsoft.com/azure-functions/dotnet:4-dotnet8.0.
Azure Functions were not running when deployed.
- Fix the output directory argument in Dockerfiles.
- Update the runtime container image used.

fix: update functions runtime image

---

scripts/dev-clean-up-template-test.sh
scripts/dev-test-templates.sh
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.API.ComponentTests/Setup/ApiFixture.cs
src/shared/xxENSONOxx.xxSTACKSxx.Shared.Messaging.Azure.ServiceBus/Extensions/DependencyInjectionExtensions.cs

Fix: Pipeline issue related to SecretResolver
CQRS template using Service Bus was broken
Added registration within Service Bus project and added pre-processor to add SERVICEBUS_CONNECTIONSTRING for Component Tests as it was required for registration...
Cqrs.AllTheThings working with a valid SERVICEBUS_CONNECTIONSTRING:
All Component Tests passing:
Notes for QA

Fix: Pipeline issue related to SecretResolver

---

src/func-aeh-listener/src/functions/xxENSONOxx.xxSTACKSxx.Listener.UnitTests/JsonMessageSerializerTests.cs
src/func-aeh-listener/src/functions/xxENSONOxx.xxSTACKSxx.Listener.UnitTests/StacksListenerTests.cs

refactor: 7752 - add unit tests

---

src/func-aeh-listener/src/functions/xxENSONOxx.xxSTACKSxx.Listener/Program.cs

Remove the issue with the function

7762 - fix the issue with the runtime

---

docs/introduction_netcore.md
docs/requirments_netcore.md
docs/testing/functional_testing_netcore.md

Update top level .NET documentation
Make the documentation easier to consume for all levels. Remove any requirements for pre-existing knowledge

8131 - Update top level .NET documentation

---

docs/quickstart/web_api/build_and_run_project_netcore.md
docs/quickstart/web_api/create_project_netcore.md

Update the quick start documentation for the simple api

Refactor: 8264 - update the documentation

---

docs/architecture/architecture_overview_netcore.md

Updated the architecture to be more readable, understandable and contain clearer links to Martin Fowlers DDD overview

refactor: 8268 make the architecture overview more readable

---

asciidoc/automated_release_notes.adoc
build/azDevOps/azure/release-notes/handlebar/extensions/custom-extensions.js
build/azDevOps/azure/release-notes/handlebar/releaseNoteTemplate.handlebars
build/azDevOps/azure/release-notes/publish-release-notes.yml

Updates the handlebar template to handle variances in available data upon deployment to master
Adds in an asciidoc detailing the release note capability
To provide users with information about the release notes
To handle discrepancies between available data in PR/merge builds.

AB#1292 and AB#1293 - Update template and documentation

---

build/azDevOps/azure/release-notes/handlebar/releaseNoteTemplate.handlebars

Minor fix to the PR template which stops it from printing "Triggered for: [blank]" when pr.sender.name is not present on a merge to master
Notes for QA

fixes AB#1294

---

scripts/expected-trees/Cqrs.AllTheThings.tree
scripts/expected-trees/Cqrs.Dynamo.tree
scripts/expected-trees/Cqrs.ServiceBus.tree
scripts/expected-trees/Cqrs.Sns.tree
scripts/expected-trees/Cqrs.tree
scripts/expected-trees/Simple.Api.AWS.tree
scripts/expected-trees/Simple.Api.Azure.tree
scripts/expected-trees/Simple.Api.tree
src/cqrs/src/api/README.md
src/cqrs/src/tests/Functional/xxENSONOxx.xxSTACKSxx.API.FunctionalTests/ReadMe.md
src/simple-api/src/api/README.md
src/simple-api/src/tests/Functional/xxENSONOxx.xxSTACKSxx.API.FunctionalTests/ReadMe.md

Remove redundant READMEs in CQRS and Simple API

8270 - Remove redundant READMEs in CQRS and Simple API

---

deploy/aws/app/kube/README.md
src/cqrs/src/api/xxENSONOxx.xxSTACKSxx.Infrastructure.IntegrationTests/CosmosDb/README.md

Update Integration Test README

8270 - Update Integration Test README

---

stackscli.yml

added deploymentMode to stackscli file
we can now pass in AKS or ACA from stacks-cli, https://github.com/Ensono/stacks-cli/pull/50

added deploymentMode to stackscli file

---

deploy/azure/app/aca/main.tf

Fix aca container name and image name
force to be lowercase otherwise it breaks if domain is uppercase

Fix aca container name

---

docs/architecture/data_storage_comsosdb_netcore.md

Update the cosmos docs in line with the external documentation

refactor: update the cosmos docs

---

README.md
docs/architecture/project_structure/cqrs_netcore.md

Update documentation to include Aspire

Feature/8377  - Aspire added to documentation

---

docs/infrastructure_aws_netcore.md
docs/infrastructure_netcore.md
docs/pipeline_gha_netcore.md
docs/pipeline_netcore.md

Update infra and pipeline docs to match Ensono Stacks.

docs: update infra and pipeline

---

README.md

fix: 8403 fix the broken link
